### ISSUE TITLE
Login in with multiple windows open cause runtime error

### ISSUE THREAD

**Issue by lefort-kara** [javydreamercsw/validation-manager#76] opened 2017-07-24 17:53 UTC
![image](https://user-images.githubusercontent.com/30300115/28625270-ae5c1708-71e9-11e7-8cc4-eaba9350325c.png)
unable to login with single window

![image](https://user-images.githubusercontent.com/30300115/28537016-786f9df4-7077-11e7-8bac-aa231cf63a5c.png)
![image](https://user-images.githubusercontent.com/30300115/28537032-82c43328-7077-11e7-9dcf-b71335334aa8.png)
 unable to login into validation manager

Steps to reproduce:
1. Go to http://eqvsrd00.sncorp.smith-nephew.com:7070/vm-demo/
2. Attempt to login with created usernames and passwords.

**Comment by javydreamercsw** [comment] 2017-07-24 18:03
Got this from the server logs:

```
java.lang.RuntimeException: The given connector with id 18 is not the one that was registered for that id
	at com.vaadin.ui.ConnectorTracker.unregisterConnector(ConnectorTracker.java:170)
	at com.vaadin.server.AbstractClientConnector.detach(AbstractClientConnector.java:646)
	at com.vaadin.ui.AbstractComponent.detach(AbstractComponent.java:701)
	at com.vaadin.server.AbstractClientConnector.detach(AbstractClientConnector.java:641)
	at com.vaadin.ui.AbstractComponent.detach(AbstractComponent.java:701)
	at com.vaadin.ui.AbstractComponent.setParent(AbstractComponent.java:579)
	at com.vaadin.ui.AbstractComponentContainer.removeComponent(AbstractComponentContainer.java:229)
	at com.vaadin.ui.TabSheet.removeComponent(TabSheet.java:205)
	at com.vaadin.ui.AbstractSingleComponentContainer.removeFromParent(AbstractSingleComponentContainer.java:185)
	at com.vaadin.ui.AbstractComponentContainer.addComponent(AbstractComponentContainer.java:211)
	at com.vaadin.ui.TabSheet.addTab(TabSheet.java:404)
	at com.vaadin.ui.TabSheet.addTab(TabSheet.java:356)
	at com.vaadin.ui.TabSheet.addTab(TabSheet.java:332)
	at net.sourceforge.javydreamercsw.validation.manager.web.ValidationManagerUI.lambda$getContentComponent$2(ValidationManagerUI.java:868)
	at java.lang.Iterable.forEach(Unknown Source)
	at net.sourceforge.javydreamercsw.validation.manager.web.ValidationManagerUI.getContentComponent(ValidationManagerUI.java:862)
	at net.sourceforge.javydreamercsw.validation.manager.web.ValidationManagerUI.updateScreen(ValidationManagerUI.java:1004)
	at net.sourceforge.javydreamercsw.validation.manager.web.ValidationManagerUI.setUser(ValidationManagerUI.java:254)
	at net.sourceforge.javydreamercsw.validation.manager.web.LoginDialog.tryToLogIn(LoginDialog.java:142)
	at net.sourceforge.javydreamercsw.validation.manager.web.LoginDialog.lambda$new$5a7d45c0$1(LoginDialog.java:69)
	at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1015)
	at com.vaadin.ui.Button.fireClick(Button.java:377)
	at com.vaadin.ui.Button$1.click(Button.java:54)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:437)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:402)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1436)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2500)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
```

**Comment by javydreamercsw** [comment] 2017-07-24 18:26
Might be related to this: https://stackoverflow.com/questions/23881573/vaadin-a-connector-with-id-xy-is-already-registered

**Comment by javydreamercsw** [comment] 2017-07-25 20:42
Duplicated with the reported and only occurs if more than one window is open for the application.

**Comment by javydreamercsw** [comment] 2017-07-26 15:18
Fix attempt on 3536629f7a281e015d4d0b186ddefe96e5869ba4. Still unable to reproduce on my environment.

**Comment by javydreamercsw** [comment] 2017-07-26 20:16
Confirmed as fixed with the latest changes.

**Comment by javydreamercsw** [comment] 2017-08-04 16:34
Confirmed as fixed by initial reporter.

**Closed by javydreamercsw** 2017-08-04 16:34 UTC
Labels: bug, in progress
